import sqlite3
import os

# Resolves the path to store.db relative to this file.
# All repositories import get_connection() from here rather than hardcoding this path.
DB_PATH = os.path.join(os.path.dirname(__file__), 'store.db')


def get_connection():
    # Returns a connection to the SQLite database.
    # row_factory allows columns to be accessed by name e.g. row["email"] instead of row[0].
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def init_db():
    # Creates all tables if they do not already exist.
    # Called once on startup from app.py.
    # Add new CREATE TABLE statements here as new entities are implemented.
    conn = get_connection()
    cursor = conn.cursor()

    # Passwords are stored as hashes generated by Flask's password hashing utility.
    # The minimum length of 60 characters ensures plain text passwords are rejected
    # at the database level regardless of which hashing library is used.
    # Address fields are optional but if any one is provided all four must be provided together.
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS customers (
            customer_id  INTEGER PRIMARY KEY AUTOINCREMENT,
            first_name   TEXT NOT NULL CHECK(length(first_name) >= 1 AND length(first_name) <= 35),
            last_name    TEXT NOT NULL CHECK(length(last_name) >= 1 AND length(last_name) <= 35),
            email        TEXT NOT NULL CHECK(length(email) >= 6 AND length(email) <= 254 AND email LIKE '%_@_%.__%' AND email NOT LIKE '% %') UNIQUE,
            phone_number TEXT CHECK(phone_number IS NULL OR (length(phone_number) >= 10 AND length(phone_number) <= 15 AND phone_number GLOB '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]*' AND phone_number NOT GLOB '*[^0-9]*')),
            password     TEXT NOT NULL CHECK(length(password) >= 60),
            street       TEXT CHECK(street IS NULL OR (street IS NOT NULL AND suburb IS NOT NULL AND state IS NOT NULL AND postcode IS NOT NULL AND length(street) >= 1 AND length(street) <= 100)),
            suburb       TEXT CHECK(suburb IS NULL OR (suburb IS NOT NULL AND street IS NOT NULL AND state IS NOT NULL AND postcode IS NOT NULL AND length(suburb) >= 1 AND length(suburb) <= 50)),
            state        TEXT CHECK(state IS NULL OR (state IS NOT NULL AND street IS NOT NULL AND suburb IS NOT NULL AND postcode IS NOT NULL AND length(state) >= 2 AND length(state) <= 3 AND state NOT GLOB '*[^A-Za-z]*')),
            postcode     TEXT CHECK(postcode IS NULL OR (postcode IS NOT NULL AND street IS NOT NULL AND suburb IS NOT NULL AND state IS NOT NULL AND length(postcode) = 4 AND postcode GLOB '[0-9][0-9][0-9][0-9]'))
        )
    ''')

    conn.commit()
    conn.close()