import json
import os
import sqlite3

from src.data.cover_cache import cache_covers

# Resolves the path to store.db relative to this file.
# All repositories import get_connection() from here rather
# than hardcoding this path.
DB_PATH = os.path.join(os.path.dirname(__file__), "store.db")

# Resolves the path to the seed file relative to this file.
# The seed file is read once on first run to populate the
# books table.
SEEDS_PATH = os.path.join(os.path.dirname(__file__), "seeds", "data.json")


def get_connection():
    # Returns a connection to the SQLite database.
    # row_factory allows columns to be accessed by name
    # e.g. row["email"] instead of row[0].
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def init_db(cover_cache_dir=None):
    # Creates all tables if they do not already exist.
    # Called once on startup from app.py.
    # cover_cache_dir is the absolute path to the folder
    # where cover images should be cached.
    # If None, cover caching is skipped.
    # Add new CREATE TABLE statements here as new entities
    # are implemented.
    conn = get_connection()
    cursor = conn.cursor()

    # Passwords are stored as hashes generated by Flask's
    # password hashing utility.
    # The minimum length of 60 characters ensures plain text
    # passwords are rejected at the database level regardless
    # of which hashing library is used.
    # Address fields are optional but if any one is provided
    # all four must be provided together.
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS customers (
            customer_id  INTEGER PRIMARY KEY AUTOINCREMENT,
            first_name   TEXT NOT NULL
                         CHECK(length(first_name) >= 1
                               AND length(first_name) <= 35),
            last_name    TEXT NOT NULL
                         CHECK(length(last_name) >= 1
                               AND length(last_name) <= 35),
            email        TEXT NOT NULL
                         CHECK(length(email) >= 6
                               AND length(email) <= 254
                               AND email LIKE '%_@_%.__%'
                               AND email NOT LIKE '% %')
                         UNIQUE,
            phone_number TEXT
                         CHECK(phone_number IS NULL
                               OR (length(phone_number) >= 10
                                   AND length(phone_number) <= 15
                                   AND phone_number GLOB
                                   '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]*'
                                   AND phone_number NOT GLOB
                                   '*[^0-9]*')),
            password     TEXT NOT NULL
                         CHECK(length(password) >= 60),
            street       TEXT
                         CHECK(street IS NULL
                               OR (street IS NOT NULL
                                   AND suburb IS NOT NULL
                                   AND state IS NOT NULL
                                   AND postcode IS NOT NULL
                                   AND length(street) >= 1
                                   AND length(street) <= 100)),
            suburb       TEXT
                         CHECK(suburb IS NULL
                               OR (suburb IS NOT NULL
                                   AND street IS NOT NULL
                                   AND state IS NOT NULL
                                   AND postcode IS NOT NULL
                                   AND length(suburb) >= 1
                                   AND length(suburb) <= 50)),
            state        TEXT
                         CHECK(state IS NULL
                               OR (state IS NOT NULL
                                   AND street IS NOT NULL
                                   AND suburb IS NOT NULL
                                   AND postcode IS NOT NULL
                                   AND length(state) >= 2
                                   AND length(state) <= 3
                                   AND state NOT GLOB
                                   '*[^A-Za-z]*')),
            postcode     TEXT
                         CHECK(postcode IS NULL
                               OR (postcode IS NOT NULL
                                   AND street IS NOT NULL
                                   AND suburb IS NOT NULL
                                   AND state IS NOT NULL
                                   AND length(postcode) = 4
                                   AND postcode GLOB
                                   '[0-9][0-9][0-9][0-9]'))
        )
    """
    )

    # Books table stores catalogue metadata for each title
    # sold in the store.
    # isbn is stored as a business attribute identifying the
    # specific edition.
    # isbn also serves as the key for fetching cover images
    # from the Open Library Covers API at
    # https://covers.openlibrary.org/b/isbn/{isbn}-M.jpg.
    # The cover URL is derived in the repository at query time
    # and is never stored here.
    # price must be zero or positive.
    # stock must be zero or positive.
    # title and author must be at least 1 character and no
    # more than 200 characters.
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS books (
            book_id      INTEGER PRIMARY KEY AUTOINCREMENT,
            title        TEXT NOT NULL
                         CHECK(length(title) >= 1
                               AND length(title) <= 200),
            author       TEXT NOT NULL
                         CHECK(length(author) >= 1
                               AND length(author) <= 200),
            isbn         TEXT
                         CHECK(isbn IS NULL
                               OR length(isbn) >= 1),
            genre        TEXT NOT NULL DEFAULT 'General'
                         CHECK(length(genre) >= 1
                               AND length(genre) <= 100),
            description  TEXT NOT NULL DEFAULT ''
                         CHECK(length(description) >= 0),
            price        REAL NOT NULL CHECK(price >= 0),
            stock        INTEGER NOT NULL DEFAULT 0
                         CHECK(stock >= 0)
        )
    """
    )

    conn.commit()
    _seed_books(conn, cover_cache_dir)
    conn.close()


def _seed_books(conn, cover_cache_dir=None):
    if not os.path.exists(SEEDS_PATH):
        return

    with open(SEEDS_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    books = data.get("books", [])
    if not books:
        return

    cursor = conn.cursor()
    cursor.execute("SELECT isbn FROM books WHERE isbn IS NOT NULL")
    existing_isbns = {row["isbn"] for row in cursor.fetchall()}

    new_books = []
    for book in books:
        isbn = book.get("isbn")
        if not isbn:
            # ISBN is required for new books so covers can be cached and
            # duplicates can be detected reliably.
            continue
        if isbn and isbn in existing_isbns:
            continue
        cursor.execute(
            """
            INSERT INTO books
                (title, author, isbn, genre,
                 description, price, stock)
            VALUES (?, ?, ?, ?, ?, ?, ?)
        """,
            (
                book.get("title", ""),
                book.get("author", ""),
                book.get("isbn"),
                book.get("genre", "General"),
                book.get("description", ""),
                book.get("price", 0.0),
                book.get("stock", 0),
            ),
        )
        if isbn:
            existing_isbns.add(isbn)
        new_books.append(book)

    conn.commit()

    if cover_cache_dir and new_books:
        cache_covers(new_books, cover_cache_dir)
