import json
import os
import sqlite3

from src.data.seeds.cover_cache import cache_covers

# Resolves the path to store.db relative to this file.
# All repositories import get_connection() from here rather
# than hardcoding this path.
DB_PATH = os.path.join(os.path.dirname(__file__), "store.db")

# Resolves the path to the seed file relative to this file.
# The seed file is read on every startup and its rows are
# upserted into the books table, so edits to it take effect
# on the next run.
SEEDS_PATH = os.path.join(os.path.dirname(__file__), "seeds", "data.json")


def get_connection():
    # Returns a connection to the SQLite database.
    # row_factory allows columns to be accessed by name
    # e.g. row["email"] instead of row[0].
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def init_db(cover_cache_dir=None):
    # Creates all tables if they do not already exist.
    # Called once on startup from app.py.
    # cover_cache_dir is the absolute path to the folder
    # where cover images should be cached.
    # If None, cover caching is skipped.
    # Add new CREATE TABLE statements here as new entities
    # are implemented.
    conn = get_connection()
    cursor = conn.cursor()

    # Passwords are stored as hashes generated by Flask's
    # password hashing utility.
    # The minimum length of 60 characters ensures plain text
    # passwords are rejected at the database level regardless
    # of which hashing library is used.
    # Address fields are optional but if any one is provided
    # all four must be provided together.
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS customers (
            customer_id  INTEGER PRIMARY KEY AUTOINCREMENT,
            first_name   TEXT NOT NULL
                         CHECK(length(first_name) >= 1
                               AND length(first_name) <= 35),
            last_name    TEXT NOT NULL
                         CHECK(length(last_name) >= 1
                               AND length(last_name) <= 35),
            email        TEXT NOT NULL
                         CHECK(length(email) >= 6
                               AND length(email) <= 254
                               AND email LIKE '%_@_%.__%'
                               AND email NOT LIKE '% %')
                         UNIQUE,
            phone_number TEXT
                         CHECK(phone_number IS NULL
                               OR (length(phone_number) >= 10
                                   AND length(phone_number) <= 15
                                   AND phone_number GLOB
                                   '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]*'
                                   AND phone_number NOT GLOB
                                   '*[^0-9]*'))
             UNIQUE,  -- one phone number per account

            password     TEXT NOT NULL
                         CHECK(length(password) >= 60),
            street       TEXT
                         CHECK(street IS NULL
                               OR (street IS NOT NULL
                                   AND suburb IS NOT NULL
                                   AND state IS NOT NULL
                                   AND postcode IS NOT NULL
                                   AND length(street) >= 1
                                   AND length(street) <= 100)),
            suburb       TEXT
                         CHECK(suburb IS NULL
                               OR (suburb IS NOT NULL
                                   AND street IS NOT NULL
                                   AND state IS NOT NULL
                                   AND postcode IS NOT NULL
                                   AND length(suburb) >= 1
                                   AND length(suburb) <= 50)),
            state        TEXT
                         CHECK(state IS NULL
                               OR (state IS NOT NULL
                                   AND street IS NOT NULL
                                   AND suburb IS NOT NULL
                                   AND postcode IS NOT NULL
                                   AND length(state) >= 2
                                   AND length(state) <= 3
                                   AND state NOT GLOB
                                   '*[^A-Za-z]*')),
            postcode     TEXT
                         CHECK(postcode IS NULL
                               OR (postcode IS NOT NULL
                                   AND street IS NOT NULL
                                   AND suburb IS NOT NULL
                                   AND state IS NOT NULL
                                   AND length(postcode) = 4
                                   AND postcode GLOB
                                   '[0-9][0-9][0-9][0-9]'))
        )
    """
    )

    # Books table stores catalogue metadata for each title
    # sold in the store.
    # isbn is the primary key. It uniquely identifies the
    # specific edition and is therefore mandatory: every book
    # must carry one. SQLite does not enforce NOT NULL on a
    # non-integer primary key on its own, so it is declared
    # explicitly here, and the CHECK rejects empty strings,
    # which would otherwise be a valid but useless key.
    # isbn also serves as the key for fetching cover images
    # from the Open Library Covers API at
    # https://covers.openlibrary.org/b/isbn/{isbn}-M.jpg.
    # The cover URL is derived in the repository at query time
    # and is never stored here.
    # price must be zero or positive.
    # stock must be zero or positive.
    # title and author must be at least 1 character and no
    # more than 200 characters.
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS books (
            isbn         TEXT NOT NULL PRIMARY KEY
                         CHECK(length(isbn) >= 1),
            title        TEXT NOT NULL
                         CHECK(length(title) >= 1
                               AND length(title) <= 200),
            author       TEXT NOT NULL
                         CHECK(length(author) >= 1
                               AND length(author) <= 200),
            genre        TEXT NOT NULL DEFAULT 'General'
                         CHECK(length(genre) >= 1
                               AND length(genre) <= 100),
            description  TEXT NOT NULL DEFAULT ''
                         CHECK(length(description) >= 0),
            price        REAL NOT NULL CHECK(price >= 0),
            stock        INTEGER NOT NULL DEFAULT 0
                         CHECK(stock >= 0)
        )
    """
    )
    # stores all the orders
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS orders (
            order_id INTEGER PRIMARY KEY AUTOINCREMENT,
            customer_id INTEGER NOT NULL,
            order_date TEXT NOT NULL,
            total_amount REAL NOT NULL,
            shipping_address TEXT,
            shipping_phone TEXT,
                FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
            )
        """
    )
    # stores all the order items, that will be used to complete an order
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS order_items (
            order_item_id INTEGER PRIMARY KEY AUTOINCREMENT,
            order_id INTEGER NOT NULL,
            book_id INTEGER NOT NULL,
            quantity INTEGER NOT NULL,
            unit_price REAL NOT NULL,
            FOREIGN KEY (order_id) REFERENCES orders(order_id),
            FOREIGN KEY (book_id) REFERENCES books(book_id)
            )
        """
    )
    # Store all invoices
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS invoices (
            invoice_id INTEGER PRIMARY KEY AUTOINCREMENT,
            order_id INTEGER NOT NULL,
            invoice_date TEXT NOT NULL,
            amount_due REAL NOT NULL,
                FOREIGN KEY (order_id) REFERENCES orders(order_id)
            )
        """
    )
    conn.commit()
    print("[startup] Database tables ready.", flush=True)
    _seed_books(conn, cover_cache_dir)
    _seed_users(conn)
    conn.close()
    print("[startup] Startup complete.", flush=True)


def _seed_books(conn, cover_cache_dir=None):
    if not os.path.exists(SEEDS_PATH):
        return

    with open(SEEDS_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    books = data.get("books", [])
    if not books:
        return

    cursor = conn.cursor()

    # isbn is the primary key, so seeding is an upsert keyed on it.
    # ON CONFLICT(isbn) DO UPDATE means a book already in the table is
    # refreshed in place from the seed file rather than skipped. This is
    # what makes edits to the seed file (for example a changed price) take
    # effect on the next run. The excluded.* values refer to the row that
    # would have been inserted, i.e. the new values from the seed file.
    # A book with no isbn cannot be a key and is skipped entirely. This is
    # deliberate: without it, a seed entry whose isbn had been removed would
    # be inserted as a brand new row, producing a duplicate title with no
    # cover. Skipping leaves any existing row for that title untouched.
    print(f"[startup] Seeding {len(books)} book(s)...", flush=True)
    seeded_books = []
    for book in books:
        isbn = book.get("isbn")
        if not isbn:
            # No isbn means no primary key. Skip silently rather than
            # creating an unkeyed duplicate.
            continue

        # If a row already exists for this title+author under a *different*
        # isbn, the isbn was corrected in the seed file. Remove the stale row
        # so the upsert below inserts under the new isbn rather than leaving
        # both records in the table.
        title = book.get("title", "")
        author = book.get("author", "")
        cursor.execute(
            "SELECT isbn FROM books WHERE title = ? AND author = ? AND isbn != ?",
            (title, author, isbn),
        )
        stale = cursor.fetchone()
        if stale:
            print(
                f"[seed] ISBN changed for '{title}': "
                f"{stale['isbn']} → {isbn}, removing old record.",
                flush=True,
            )
            cursor.execute("DELETE FROM books WHERE isbn = ?", (stale["isbn"],))

        cursor.execute(
            """
            INSERT INTO books
                (isbn, title, author, genre,
                 description, price, stock)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(isbn) DO UPDATE SET
                title       = excluded.title,
                author      = excluded.author,
                genre       = excluded.genre,
                description = excluded.description,
                price       = excluded.price,
                stock       = excluded.stock
        """,
            (
                isbn,
                book.get("title", ""),
                book.get("author", ""),
                book.get("genre", "General"),
                book.get("description", ""),
                book.get("price", 0.0),
                book.get("stock", 0),
            ),
        )
        seeded_books.append(book)

    conn.commit()
    print(f"[startup] {len(seeded_books)} book(s) seeded.", flush=True)

    # cache_covers is idempotent: it skips any cover already on disk, so it
    # is safe to pass every seeded book on every run. Only genuinely missing
    # covers trigger a network fetch.
    if cover_cache_dir and seeded_books:
        print("[startup] Checking cover image cache...", flush=True)
        cache_covers(seeded_books, cover_cache_dir)


def _seed_users(conn):
    if not os.path.exists(SEEDS_PATH):
        return

    with open(SEEDS_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    users = data.get("users", [])
    if not users:
        return

    print(f"[startup] Seeding {len(users)} user(s)...", flush=True)
    cursor = conn.cursor()

    # email is the unique key for customers, so seeding is an upsert keyed on
    # it. ON CONFLICT(email) DO UPDATE refreshes profile fields in place from
    # the seed file so edits take effect on the next run. Password is excluded
    # from the update so that a real user who registered with a seed email and
    # later changed their password is not silently overwritten.
    # A user with no email cannot be keyed and is skipped entirely.
    # A user with no password hash would produce an unusable account and is
    # also skipped. Phone number has its own UNIQUE constraint; if two seed
    # entries carry the same number the second is skipped with a warning rather
    # than crashing the whole startup.
    for user in users:
        email = user.get("email")
        password = user.get("password")
        if not email:
            # No email means no unique key — skip silently.
            continue
        if not password:
            # No password hash means the account would be unusable — skip silently.
            continue
        try:
            cursor.execute(
                """
                INSERT INTO customers
                    (first_name, last_name, email, phone_number, password,
                     street, suburb, state, postcode)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT(email) DO UPDATE SET
                    first_name   = excluded.first_name,
                    last_name    = excluded.last_name,
                    phone_number = excluded.phone_number,
                    street       = excluded.street,
                    suburb       = excluded.suburb,
                    state        = excluded.state,
                    postcode     = excluded.postcode
                """,
                (
                    user.get("first_name", ""),
                    user.get("last_name", ""),
                    email,
                    user.get("phone_number") or None,
                    password,
                    user.get("street") or None,
                    user.get("suburb") or None,
                    user.get("state") or None,
                    user.get("postcode") or None,
                ),
            )
        except sqlite3.IntegrityError as e:
            # Most likely a duplicate phone_number. Skip this entry rather
            # than aborting the whole seed run.
            print(f"[seed] skipped user {email!r}: {e}", flush=True)

    conn.commit()
    print(f"[startup] {len(users)} user(s) seeded.", flush=True)
